Traceback (most recent call last):
  File "/Users/alinaxu/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/alinaxu/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alinaxu/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/alinaxu/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/alinaxu/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/alinaxu/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/alinaxu/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alinaxu/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from causaldm.learners.CPL4.CMAB import _env_realCMAB as _env
env = _env.Single_Contextual_Env(seed = 0, Binary = False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mEOFError[0m                                  Traceback (most recent call last)
[0;32m/var/folders/9j/vb5nb4rd5bx0gr1q5ytx9q600000gn/T/ipykernel_69354/1670608188.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0mcausaldm[0m[0;34m.[0m[0mlearners[0m[0;34m.[0m[0mCPL4[0m[0;34m.[0m[0mCMAB[0m [0;32mimport[0m [0m_env_realCMAB[0m [0;32mas[0m [0m_env[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0menv[0m [0;34m=[0m [0m_env[0m[0;34m.[0m[0mSingle_Contextual_Env[0m[0;34m([0m[0mseed[0m [0;34m=[0m [0;36m0[0m[0;34m,[0m [0mBinary[0m [0;34m=[0m [0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/opt/anaconda3/lib/python3.9/site-packages/causaldm/learners/CPL4/_util_online.py[0m in [0;36mwrapper[0;34m(self, *args, **kwargs)[0m
[1;32m    221[0m                     [0;32mif[0m [0msieve[0m[0;34m([0m[0mattr[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    222[0m                         [0msetattr[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mattr[0m[0;34m,[0m [0mval[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 223[0;31m             [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    224[0m         [0;32mreturn[0m [0mwrapper[0m[0;34m[0m[0;34m[0m[0m
[1;32m    225[0m     [0;32mreturn[0m [0m_autoargs[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/causaldm/learners/CPL4/CMAB/_env_realCMAB.py[0m in [0;36m__init__[0;34m(self, seed, Binary, leave_drama)[0m
[1;32m     11[0m         [0mnp[0m[0;34m.[0m[0mrandom[0m[0;34m.[0m[0mseed[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mseed[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m         [0mrandom[0m[0;34m.[0m[0mseed[0m[0;34m([0m[0mself[0m[0;34m.[0m[0mseed[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 13[0;31m         [0mself[0m[0;34m.[0m[0mdat[0m [0;34m=[0m [0mget_movielens[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m         [0mself[0m[0;34m.[0m[0mN[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mdat[0m[0;34m[[0m[0;34m'Xs'[0m[0;34m][0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m         [0mself[0m[0;34m.[0m[0mleave_drame[0m [0;34m=[0m [0mleave_drama[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.9/site-packages/causaldm/learners/CPL4/CMAB/_env_realCMAB.py[0m in [0;36mget_movielens[0;34m()[0m
[1;32m     67[0m     [0;32mwith[0m [0mopen[0m[0;34m([0m[0mdata_dir[0m[0;34m,[0m [0;34m"rb"[0m[0;34m)[0m [0;32mas[0m [0mfp[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     68[0m         [0mMovieLens[0m [0;34m=[0m [0mpickle[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mfp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 69[0;31m         [0mMovieLens[0m [0;34m=[0m [0mpickle[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mfp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     70[0m     [0;32mreturn[0m [0mMovieLens[0m[0;34m[0m[0;34m[0m[0m

[0;31mEOFError[0m: Ran out of input
EOFError: Ran out of input

